urls.py
from django.urls import path 
from . import views 

app_name = 'app' 



urlpatterns = [
    path('', views.index, name='index'),
    # path('peliculas/', views.movies, name='movies'),
    # path('peliculas/<int:id>', views.movie, name='movie'),
    # path("categorias/", views.categories, name="categories"),
  
# URLS anonimo
    
    path('inicio1/', views.inicio1, name='inicio1'),
    path('categorias1/', views.categorias1, name='categorias1'),
    path('categorias1/<int:id>/', views.categoria1, name='categoria1'),
    path('verpelis1/', views.verpelis1, name='verpelis1'),
    path('verpelis1/<int:id>/', views.verpeli1, name='verpeli1'),


    path('ultipeli1/', views.ultipeli1, name='ultipeli1'),
    path('cartelera1/', views.cartelera1, name='cartelera1'),
    path('buscarpeli1/', views.buscarpeli1, name='buscarpeli1'),
 
    path('ranking1/', views.ranking1, name='ranking1'),
   
# URLS usuario

    path('inicio2/', views.inicio2, name='inicio2'),
    path('categorias2/', views.categorias2, name='categorias2'),
    path('categorias2/<int:id>/', views.categoria2, name='categoria2'),
    path('verpelis2/', views.verpelis2, name='verpelis2'),
    path('verpelis2/<int:id>/', views.verpeli2, name='verpeli2'),
    path('ultipeli2/', views.ultipeli2, name='ultipeli2'),
    path('cartelera2/', views.cartelera2, name='cartelera2'),
    path('buscarpeli2/', views.buscarpeli2, name='buscarpeli2'),
    path('ranking2/', views.ranking2, name='ranking2'),

 # URLS admin

    path('inicio3/', views.inicio3, name='inicio3'),
    path('listacategoria3/', views.listacategoria3, name='listacategoria3'),
    path('listapeli3/', views.listapeli3, name='listapeli3'),
    path('crearadmin3/', views.crearadmin3, name='crearadmin3'),
    path('crearpelicula3/', views.crearpelicula3, name='crearpelicula3'),
    
    path('listacategoria3/', views.listacategoria3, name='listacategoria3'),
    path('listacategoria3/crear/', views.crearcategoria3, name='crearcategoria3'),
    path('listacategoria3/crear_post/', views.post_crear_categoria, name="post_crear_categoria"),
    # path('crearcategoria3/crear_post', views.crearcategoria3, name='crearcategoria3'), 
    path('listapeli3/', views.listapeli3, name='listapeli3'),
    path('listapeli3/crear/', views.crearpelicula3, name='crearpelicula3'),
    path('listapeli3/crear_post/', views.post_crear_pelicula, name="post_crear_pelicula"),
    

    path('editarpelicula3/', views.editarpelicula3, name='editarpelicula3'),
    path('verpelis3/', views.verpelis3, name='verpelis3'),
    path('verpelis3/<int:id>/', views.verpeli3, name='verpeli3'),

# URLS registros
    
    path('login/', views.login, name='login'),
    path('post_login/', views.post_login, name='post_login'),
    path('registro/', views.registro, name='registro'),
    path('post_registro/', views.post_registro, name='post_registro'),
    path('logout/', views.salir, name='salir'),

    path('olvidecontraseña/', views.olvidecontraseña, name='olvidecontraseña'),
    path('nuevacontraseña/', views.nuevacontraseña, name='nuevacontraseña'),
    

]

templates/app/baseanonimo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  
    <title>
        {% block titulo %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'app/css/adminlte.min.css' %}">
    
</head>

<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand"  href="{% url 'app:inicio1' %}" >RankingMovie <img class="d-block w-100" ></a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:inicio1' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:ranking1' %}">Ranking</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:cartelera1' %}">Cartelera</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:categorias1' %}">Categoria</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:ultipeli1' %}">Ultimas Peliculas</a>
          </li>
          </ul>
          
          <form class="form-inline my-2 my-lg-0" method="POST" action='/app/buscarpeli1/'>
            <input class="form-control mr-sm-2" name="busca" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          </form>
          
          <form class="form-inline my-2 my-lg-0">

            
            <a href="{% url 'app:from_login' %}"> <button type="button" class="btn btn-outline-info">Ingresar</button></a>
            <a href="{% url 'app:registro' %}"> <button type="button" class="btn btn-outline-info">Registrarse</button></a>
          </form>
        </div>
      </nav>
    </header>

    {% block contenido%}
    
  

    {% endblock %}

</body>

templates/app/baseusuario.html
{{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>
        {% block titulo %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'app/css/adminlte.min.css' %}">
    
</head>

<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand"  href="{% url 'app:inicio2' %}" >RankingMovie <img class="d-block w-100" ></a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:inicio2' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:ranking2' %}">Ranking</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:cartelera2' %}">Cartelera</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:categorias2' %}">Categoria</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:ultipeli2' %}">Ultimas Peliculas</a>
          </li>
          </ul>
          
          <form class="form-inline my-2 my-lg-0" action='/app/buscarpeli2/'>
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          </form>
          
          <form class="form-inline my-2 my-lg-0">
            
            <a hhref="{% url 'app:salir' %}"> <button type="button" class="btn btn-outline-dark">salir </button></a>
            
    
          </form>
        </div>
      </nav>
</header>

    {% block contenido %}
  

    {% endblock %}

</body>

templates/app/buscarpeli1.html
{% extends "app/baseanonimo.html"%}
{% load static %}

{% block titulo %}
Buscar pelicula anonimo
{% endblock%}

{% block contenido %}
<h1 class="display-1">Buscar pelicula anonimo</h1>




<div class="content">
    <div class="card-deck" style="margin: 20px 50px">
      <div class="card">
        <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
        <div class="card-body">
          <h1 class="card-title"><a href="http://127.0.0.1:8000/app/peliculas/1">pelicula 1</a></h1>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
       
           </div>
      </div>
      <div >
       
        </div>
      </div>
      <div >
      
        </div>
      </div>
      <div >
        
        
      </div>
      <div >
        
      </div>
      <div >
      
      </div>
    </div>
  </div>
  <div class="content">
      <div class="card-deck" style="margin: 20px 50px">
        <div class="card">
          <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
          <div class="card-body">
            <h1 class="card-title"><a href="http://127.0.0.1:8000/app/peliculas/2">pelicula 2</a></h1>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
         
             </div>
        </div>
        <div >
         
          </div>
        </div>
        <div >
        
          </div>
        </div>
        <div >
          
          
        </div>
        <div >
          
        </div>
        <div >
        
        </div>
      </div>
    </div>

  
    <div class="content">
      <div class="card-deck" style="margin: 20px 50px">
        <div class="card">
          <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
          <div class="card-body">
            <h1 class="card-title"><a href="http://127.0.0.1:8000/app/peliculas/3">pelicula 3</a></h1>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
         
             </div>
        </div>
        <div >
         
          </div>
        </div>
        <div >
        
          </div>
        </div>
        <div >
          
          
        </div>
        <div >
          
        </div>
        <div >
        
        </div>
      </div>
    </div>
    <div class="content">
      <div class="card-deck" style="margin: 20px 50px">
        <div class="card">
          <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
          <div class="card-body">
            <h1 class="card-title"><a href="http://127.0.0.1:8000/app/peliculas/4">pelicula 4</a></h1>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
         
             </div>
        </div>
        <div >
         
          </div>
        </div>
        <div >
        
          </div>
        </div>
        <div >
          
          
        </div>
        <div >
          
        </div>
        <div >
        
        </div>
      </div>
    </div>

    <div class="content">
      <div class="card-deck" style="margin: 20px 50px">
        <div class="card">
          <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
          <div class="card-body">
            <h1 class="card-title"><a href="http://127.0.0.1:8000/app/peliculas/5">pelicula 5</a></h1>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
         
             </div>
        </div>
        <div >
         
          </div>
        </div>
        <div >
        
          </div>
        </div>
        <div >
          
          
        </div>
        <div >
          
        </div>
        <div >
        
        </div>
      </div>
    </div>



{% endblock %}

templates/app/categorias2.html
{% extends "app/baseusuario.html"%}
{% load static %}

{% block titulo %}
Categoria usuario
{% endblock%}

{% block contenido %}
<h1 class="display-1">Categorias Usuario</h1>



<div class="content">
  {% for c in lista_categorias %}
    <div class="card-deck" style="margin: 20px 50px">
      <div class="card">
        <!--img src="/img/3.jpg" class="card-img-top" alt="..."-->
        
        <div class="card-body">
          <h1 class="display-1">
            <a href="{% url 'app:categoria2' c.id %}">
            {{ c.nombre }}
            </a>
        </h1>   
        </div>
        
      </div>
     
    </div>
    {% endfor %} 
  </div>

 
  



{% endblock %}

templates/app/crearadmin3.html
{% extends "app/baseadmin.html"%}
{% load static %}

{% block titulo %}
crear administrador
{% endblock%}

{% block contenido %}


<form action="{% url 'app:post_crear_admin3' %}" method="post">
  {% csrf_token %}
<h1 class="display-1">crear administrador</h1>


<div class="row no-gutters bg-light position-relative">
    <div class="col-md-6 mb-md-0 p-md-4">
       <form>
        <form>
                  <div class="form-group row">
                          
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Username" name="username">
                </div>
                </div>
                <div class="form-group row">
                  
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Nombre</label>
                    <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Nombre" name="nombre">
                </div>
                </div>
                <div class="form-group row">
                  
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Apellido</label>
                    <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Apellido" name="apellido">
                </div>
                </div>

            <div class="form-group row">
              <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="correo" >
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-2 col-form-label">Contraseña</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3"placeholder="Contraseña" name="contraseña">
              </div>
            </div>
           
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Agregar </button>
              </div>
            </div>
          </form>

      </form>
  </div>
  <div class="col">
    <table class="table table-striped projects">
      <thead>
          <tr>
              <th style="width: 20%">
                  Nombre
              </th>
              <th style="width: 20%">
                  Apellido
              </th>
              <th style="width: 30%">
                Email
            </th>
              <!-- <th style="width: 10%" class="text-center">
                Contraseña
              </th> -->
              <th style="width: 10%">
                Editar
              </th>
              
          </tr>
      </thead>
      <tbody>
        {% for c in lista_usuario %}
          <tr>
              <td>
                {{ c.first_name }}
              </td>
              <td>
                
                  <a>
                  {{ c.last_name }}
                  </a>
                

              </td>
              <td>
                <a>
                  {{ c.email }}
                </a>

            </td>
           
              <td class="project-state">
                <a class="btn btn-primary btn-sm" href="#">
                    <i class="far fa-edit">editar</i>
                </a>
              </td>
              {% endfor %} 
          </tr>

          
      
        
    </tr>
            
        </td>
      </tbody>
  </table>
  </div>
</div>
{% endblock %}

templates/app/crearcategoria3.html
{% extends "app/baseadmin.html"%}
{% load static %}

{% block titulo %}
Categorias categoria
{% endblock%}

{% block contenido %}
<h1 class="display-1">Crear categoria</h1>


<div class="row no-gutters bg-light position-relative">
    <div class="col-md-6 mb-md-0 p-md-4">
       
        <form action="{% url 'app:post_crear_categoria' %}" method="post">
          {% csrf_token %}
                <div class="form-group row">
                  
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Nombre</label>
                    <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Nombre de categoria" name="nombre"> 
                </div>
                </div>
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Agregar </button>
              </div>
            </div>
           
          </form>
    </div>
      <div class="col">
          <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 80%">
                        Categoria
                    </th>
                    <th style="width: 10%">
                      Editar
                    </th>
                    <th style="width: 10%">
                      Eliminar
                    </th>
                    
                </tr>
            </thead>

            <tbody>
              {% for c in lista_categorias %}
              <tr>
                  <td>
                    {{ c.nombre }}
                  </td>
                  
                  <td class="project-state">
                    <a class="btn btn-primary btn-sm" href="#">
                        <i class="far fa-edit">editar</i>
                    </a>
                  </td>
                  
                  <td class="project-state">
                    <a class="btn btn-primary btn-sm" href="#">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                  </td>
              </tr>
              {% endfor %} 
            </tbody>
        </table>
      </div>

  </div>
</div>


{% endblock %}

templates/app/inicio1.html
{% extends "app/baseanonimo.html"%}
{% load static %}

{% block titulo %}
Inicio anonimo
{% endblock%}

{% block contenido %}




<div class="content">
 
  <div class="row">
    <div class="col"></div>
      <div class="col">
    {% for c in cartelera %} 
    
    {% if c.id == 1 %}

        <div class="small-box bg-danger">
          <div class="inner">
            <h3>{{ c.titulo }}</h3>
            <p>{{ c.anio }}</p>
          </div>
          <a href="{% url 'app:verpeli1' c.id %}" class="small-box-footer">
            Ver
          </a>
        </div>
    </div>
      {% endif %}
        
      {% if c.id == 2 %}
    <div class="col">
      <!-- small card -->
      <div class="small-box bg-info">
        <div class="inner">
          <h3>{{ c.titulo }}</h3>
          <p>{{ c.anio }}</p>
        </div>
        <a href="{% url 'app:verpeli1' c.id %}" class="small-box-footer">
          Ver
        </a>
      </div>
      
    </div>
    {% endif %}
    <!-- ./col -->
    
    {% if c.id == 3 %}
    <div class="col">
      <!-- small card -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>{{ c.titulo }}</h3>
          <p>{{ c.anio }}</p>
        </div>
        <a href="{% url 'app:verpeli1' c.id %}" class="small-box-footer">
          Ver
        </a>
      </div>
    </div>
    {% endif %}
   
    
    <!-- ./col -->
    {% endfor %} 
    <div class="col">
    </div>
  </div>

</div>

</div>

  <ul>
   
  <!-- Content Wrapper. Contains page content -->
  {% for c in lista_categorias %}
  
  <div class="content">
        <div class="row">
        <div class="col" >
          <h1> {{ c.nombre }}</h1>
        </div>
        <div class="col-9" >
            
        </div>
        <div class="col">
         <a href="{% url 'app:categoria1' c.id %}"> <button type="button" class="btn btn-link" >Ver lista</button></a>
        </div>
    </div>
    </div>
    

    
    <div class="card-deck" style="margin: 20px 50px">
      {% for p in c.peliculas.all %}
      <div class="card text-white bg-info mb-3">
        <div class="card-body">
            <h3 class="card-title">{{ p.titulo }}</h3>
            <p class="card-text">{{ p.anio }}</small></p>
            <a href="{% url 'app:verpeli1' p.id %}"><button type="button" class="btn btn-outline-light" >Ver</button></a>
         </div>
       </div>
      {% endfor %} 
      
    </div>
    
  </div>
  {% endfor %} 


{% endblock %}

templates/app/inicio2.html
{% extends "app/baseusuario.html"%}
{% load static %}

{% block titulo %}
Inicio usuario
{% endblock%}

{% block contenido %}



<div class="content">
 
    <div class="row">
      <div class="col"></div>
        <div class="col">
      {% for c in cartelera %} 
      
      {% if c.id == 1 %}

          <div class="small-box bg-danger">
            <div class="inner">
              <h3>{{ c.titulo }}</h3>
              <p>{{ c.anio }}</p>
            </div>
            <a href="{% url 'app:verpeli2' c.id %}" class="small-box-footer">
              Ver
            </a>
          </div>
      </div>
        {% endif %}
          
        {% if c.id == 2 %}
      <div class="col">
        <!-- small card -->
        <div class="small-box bg-info">
          <div class="inner">
            <h3>{{ c.titulo }}</h3>
            <p>{{ c.anio }}</p>
          </div>
          <a href="{% url 'app:verpeli2' c.id %}" class="small-box-footer">
            Ver
          </a>
        </div>
        
      </div>
      {% endif %}
      <!-- ./col -->
      
      {% if c.id == 3 %}
      <div class="col">
        <!-- small card -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3>{{ c.titulo }}</h3>
            <p>{{ c.anio }}</p>
          </div>
          <a href="{% url 'app:verpeli2' c.id %}" class="small-box-footer">
            Ver
          </a>
        </div>
      </div>
      {% endif %}
     
      
      <!-- ./col -->
      {% endfor %} 
      <div class="col">
      </div>
    </div>

  </div>

</div>

  <ul>
   
  <!-- Content Wrapper. Contains page content -->
  {% for c in lista_categorias %}
  <div class="content">
        <div class="row">
        <div class="col" >
          <h1> {{ c.nombre }}</h1>
        </div>
        <div class="col-9" >
            
        </div>
        <div class="col">
          <a href="{% url 'app:categoria2' c.id %}"> <button type="button" class="btn btn-link" >Ver lista</button></a>
        </div>
    </div>
    </div>
    

    
    <div class="card-deck" style="margin: 20px 50px">
      {% for p in c.peliculas.all %}
      
      <div class="card text-white bg-info mb-3">
        <div class="card-body">
            <h3 class="card-title">{{ p.titulo }}</h3>
            <p class="card-text">{{ p.anio }}</small></p>
            <a href="{% url 'app:verpeli2' p.id %}"><button type="button" class="btn btn-outline-light" >Ver</button></a>
         </div>
       </div>
       
      
      {%endfor%}
      
      
      
    </div>
    
  </div>
  {% endfor %} 


{% endblock %}

templates/app/listacategoria3.html
{% extends "app/baseadmin.html"%}
{% load static %}

{% block titulo %}
Lista de categoria
{% endblock%}

{% block contenido %}
<h1 class="display-1">Lista de categoria admin</h1>

<a href="{% url 'app:crearcategoria3' %}" >  <button type="submit" class="btn btn-primary"> Crear categoria</button> </a>
<br>
<br>
<div class="col">
    <table class="table table-striped projects">
      <thead>
          <tr>
              <th style="width: 10%"style="text-align: center;">
                Categoria
              </th>
              <th style="width: 10%"style="text-align: center;">
                Editar
              </th>
              <th style="width: 10%"style="text-align: center;">
                Eliminar
              </th>
              
          </tr>
      </thead>

      <tbody>
        {% for c in lista_categorias %}
          <tr>
              <td>
                {{ c.nombre }}
              </td>
              
              <td class="project-state">
                <a class="btn btn-primary btn-sm" href="#">
                    <i class="far fa-edit">editar</i>
                </a>
              </td>
              
              <td class="project-state">
                <a class="btn btn-primary btn-sm" href="#">
                  <i class="fas fa-trash-alt"></i>
                </a>
              </td>
          </tr>
          {% endfor %}          
      </tbody>
  </table>


{% endblock %}

templates/app/listapeli3.html
{% extends "app/baseadmin.html"%}
{% load static %}

{% block titulo %}
Lista de peliculas
{% endblock%}

{% block contenido %}
<h1 class="display-1">Lista de peliculas admin</h1>

<a href="{% url 'app:crearpelicula3' %}" >  <button type="submit" class="btn btn-primary"> Crear pelicula</button> </a>
<br>
<br>

<div class="col">
    <table class="table table-striped projects">
      <thead>
          <tr>
              <th style="width: 10%">
                  Pelicula
              </th>
              <th style="width: 10%">
                Año
              </th>
              <th style="width: 10%">
                En cartelera
              </th>
              <th style="width: 5%">
                Editar
              </th>
              <th style="width: 5%">
                Eliminar
              </th>
              
          </tr>
      </thead>

      <tbody>
        {% for p in lista_peliculas%}
          <tr>
              <td>
                {{ p.titulo }}
              </td>
              <td>
                {{ p.anio }}
              </td>
              <td>
                {% if p.enCartelera == 1 %}
                  si
                  {% else %}
                     no
                {% endif %}
                
              </td>
              
              <td class="project-state">
                <a class="btn btn-primary btn-sm" href="#">
                    <i class="far fa-edit">editar</i>
                </a>
              </td>
              
              <td class="project-state">
                <a class="btn btn-primary btn-sm" href="#">
                  <i class="fas fa-trash-alt"></i>
                </a>
              </td>
              
          </tr>
          {% endfor %}          
      </tbody>
  </table>
</div>


{% endblock %}

templates/app/login.html
{% extends "app/baselogin.html"%}
{% load static %}

{% block titulo %}
login
{% endblock%}

{% block login-box%}
Iniciar sesion
{% endblock %}

{% block box%}


<form action="{% url 'app:post_login' %}" method="post">
  {% csrf_token %}
    <div class="input-group mb-3">
      <input type="email" class="form-control" placeholder="Correo"name="correo">
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-envelope"></span>
        </div>
      </div>
    </div>
    <div class="input-group mb-3">
      <input type="password" class="form-control" placeholder="Contraseña" name="contraseña">
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-lock"></span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-8">
        <div class="icheck-primary">
          <input type="checkbox" id="remember">
          <label for="remember">Recordar</label>
        </div>
      </div>
      <!-- /.col -->
      <div class="col-4">
        <button type="submit" class="btn btn-primary btn-block">Entrar</button>
      </div>
      <!-- /.col -->
    </div>
  </form>
  <!-- /.social-auth-links -->

  <p class="mb-1">
    <a href="{% url 'app:olvidecontraseña' %}">Se me olvido mi contraseña</a>
  </p>
  <p class="mb-0">
    <a href="{% url 'app:registro' %}" class="text-center">Registrar</a>
  </p>
</form>
{% endblock %}
<!-- /.login-card-body -->

templates/app/movies.html
{% extends "app/base.html"%}
{% load static %}

{% block titulo %}
Peliculas
{% endblock%} 

{% block contenido %}
    <h1>Peliculas</h1>
    <h2>Holaaaaa</h2>
    <p>El autor es {{autor}} y tiene {{edad}}</p>
    <ul>
        {% for pelicula in peliculas %}
            <li>{{ pelicula }}</li>
        {% endfor %}
    </ul>
    <img src="{% static 'app/img/tierno.jpg' %}" alt="tierno" width="150px" height="250px">
    <table border="1" width="50%">
        <tr>
            <th>Actor</th>
            <th>Edad</th>
            <th>Pais</th>
        </tr>
        {% for actor in actores%}
            <tr>
                <td>{{actor.nombre}}</td>
                <td>{{actor.edad}}</td>
                <td>{{actor.pais}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/app/verpelis2.html
{% extends "app/baseusuario.html"%}
{% load static %}

{% block titulo %}
Lista de peliculas
{% endblock%}

{% block contenido %}
<h1 class="display-1">Lista de peliculas usuario</h1>


<div class="col">
    <table class="table table-striped projects">
      <thead>
          <tr>
              <th style="width: 10%">
                  Pelicula
              </th>
              <th style="width: 10%">
                Año
              </th>
              <th style="width: 10%">
                En cartelera
              </th>
             
              
          </tr>
      </thead>

      <tbody>
        {% for p in lista_peli%}
          <tr>
              <td>
                <a href="{% url 'app:verpeli2' p.id %}">
                    {{ p.titulo }}
                </a>
                
              </td>
              <td>
                {{ p.anio }}
              </td>
              <td>
                {% if p.enCartelera == 1 %}
                  si
                  {% else %}
                     no
                {% endif %}
                
              </td>
              
          </tr>
          {% endfor %}          
      </tbody>
  </table>
</div>


{% endblock %}